name: Bedwars
version: 4.1.0
api: [3.5.1, 3.5.2]
main: Bluplayz\BedWars
author: NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
